### PR TITLE
pin sphinx to a sane (aka non 1.3) version

### PR DESCRIPTION
**Pull request by amueller**
No idea how to test that though.

### CODE REVIEW

**Comment by ogrisel** [comment]
Under python 2.7 (e.g. in a venv) you should be able to do:

```
pip install -r requirements.txt
python docbuilder.py
```

and then launch the salt-ssh command included in the output.

**Comment by ogrisel** [comment]
I would like to switch to docker to make it easier to onboard new maintainers on this but I could not find the time to do the migration away from salt.

**Comment by ogrisel** [comment]
You need to put the private key `docbuilder_rsa` file I had send you by email in the past (I think) next to the public key file in the `sklearn-docbuilder` repo folder.

**Comment by ogrisel** [comment]
I applied the change successfully and merged this PR. You can always re-run the script on your side, it should be idempotent.

The next cron scheduled doc build should happen in less than 10 min.

**Comment by amueller** [comment]
awesome, looks like it worked.

**Pull request merged**
